### ISSUE TITLE
Faltando documentação

### ISSUE THREAD

**Issue by wandersonsousa** [phelyppe-matheus/fake_low_lvl_language#1]
Não consegui usar, gerando erro, um tutorial testando serial legal

**Comment by PhePheMath** [comment]
Vlw pelo feedbackEm 22 de abr de 2021 23:17, "W.Sousa" ***@***.***> escreveu:

Não consegui usar, gerando erro, um tutorial testando serial legal

**Comment by phelyppe-matheus** [comment]
> Não consegui usar, gerando erro, um tutorial testando serial legal

vlw pelo feedback

**Comment by phelyppe-matheus** [comment]
A documentação deu certo, o erro a gnt deixa pra mais tarde kk
